### ISSUE TITLE
merge_bold.py

### ISSUE THREAD

**Issue by noelpimentel** [berkeley-stat159/project-kappa#19]
This only works if you're in the ds105 directory (Ideally want it to work wherever)

Code should be more flexible (a def or class that takes in 6 or fewer arguments, i.e. the subjects, and saves their respective fMRI data into variables/displays their shape/etc.)

Bear with me, I quickly wrote this code in order to have access to the data for preliminary analysis.

@imranyousuf @changzheng1993 @giancarloescobar

**Comment by changzheng1993** [comment]
Before using the function, you should import nibabel as nib, import numpy as np, import os

**Comment by imranyousuf** [comment]
I will work on this
