### ISSUE TITLE
sub_to_nii

### ISSUE THREAD

**Issue by noelpimentel** [berkeley-stat159/project-kappa#25]
See #19

**Comment by imranyousuf** [comment]
Will work on this

**Comment by imranyousuf** [comment]
Done will push tonight

**Comment by imranyousuf** [comment]
I fixed the issue change the path of 'sub001' to '../../data/fmri_data/ds105/sub001' and it should work.
for example if you want to run high_res.py add the following lines at the end:
a,b = highRes_data('../../data/fmri_data/ds105/sub001', 'task001_run001')
print(a.shape)

to run just to python high_res.py
