### ISSUE TITLE
Appointment

### ISSUE THREAD

**Issue by changzheng1993** [berkeley-stat159/project-kappa#40]
Tuesday, 13:00
@jarrodmillman

**Comment by jarrodmillman** [comment]
It looks like you haven't made any progress this week.  I am getting worried that you won't have much accomplished by the end of the semester, if you don't start working on your project soon.  Also if you don't have any preliminary results when we meet on Tuesday, it will be difficult to provide you with useful feedback.

Remember the project is 55% of your grade.

Please review the grading criteria:
http://www.jarrodmillman.com/rcsds/notes/rubric.pdf

As well as my comments from lecture 22:
http://www.jarrodmillman.com/rcsds/lectures/day22.html
