### ISSUE TITLE
Install mvpa2 library

### ISSUE THREAD

**Issue by changzheng1993** [berkeley-stat159/project-kappa#53]
@jarrodmillman 

I really appreciate your helps at noon today. 
However, I still have a problem to install mvpa2. I have searched the problem on the Internet, but I still cannot solve it.

Here is my codes:

calvisitor-10-105-131-21:~ apple$ sudo pip install pymvpa2
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-5kwb41dp/pymvpa2

Could you please help me with these issues?  I really appreciate your helps!

**Comment by noelpimentel** [comment]
@changzheng1993 I got it working on my and @giancarloescobar laptop
I had to install PCRE and SWIG to get it to work, also I installed it through the GitHub method
