### ISSUE TITLE
Update the Makefile with commands to download and verify your data.

### ISSUE THREAD

**Issue by gcescobar13** [berkeley-stat159/project-kappa#6]
This one is difficult. Might need assistance during OH @jarrodmillman @rossbar. 
@noelpimentel @changzheng1993

**Comment by imranyousuf** [comment]
I will take a look into it

**Comment by gcescobar13** [comment]
@imranyousuf thank you!

**Comment by gcescobar13** [comment]
@imranyousuf have you had any luck making this work?
We're also looking to meet up this Thursday and Friday, are you available?

**Comment by imranyousuf** [comment]
I was not able to look into it. I am free on Friday after 6. I have a midterm on Thursday (CS170) and Monday(CS186) but I am free after that

**Comment by imranyousuf** [comment]
Let me see if I can get it done today :)

**Comment by imranyousuf** [comment]
I was not able to do it ? wanna meet at 6pm friday?

**Comment by rossbar** [comment]
How large is your data? You guys should take a run at implementing `make data`, even if it's only for a subset of your actual dataset. For instance, if you have multiple subjects, you can start with a single subject.

**Comment by imranyousuf** [comment]
Done and the code is pushed.
