### ISSUE TITLE
I am going to merge dev with master tonight at 3:00 am

### ISSUE THREAD

**Issue by imranyousuf** [berkeley-stat159/project-kappa#63]
the dev branch is almost 30 commits ahead I will merge dev to master so that we have a current master and still develop on dev branch. Let me know if there is something that does not absolutely work then I will not merge those files. @noelpimentel @giancarloescobar  @changzheng1993

**Comment by changzheng1993** [comment]
dont merge. we have some files/code that will be deleted. 
we'll do that later

**Comment by imranyousuf** [comment]
ok great. Thanks for letting me know

**Comment by imranyousuf** [comment]
Done, please only do pull request to master.
