### ISSUE TITLE
Design Matrix

### ISSUE THREAD

**Issue by changzheng1993** [berkeley-stat159/project-kappa#70]
I wil finish the design matrix as soon as possible today

**Comment by noelpimentel** [comment]
@changzheng1993  I'm going to work on my energy paper, can you keep me up to date with any progress.

**Comment by imranyousuf** [comment]
btw 
I fixed the issue change the path of 'sub001' to '../../data/fmri_data/ds105/sub001' and it should work.
for example if you want to run high_res.py add the following lines at the end:
a,b = highRes_data('../../data/fmri_data/ds105/sub001', 'task001_run001')
print(a.shape)

to run just to python high_res.py
