### ISSUE TITLE
What is the response variable?

### ISSUE THREAD

**Issue by changzheng1993** [berkeley-stat159/project-kappa#73]
I already had design matrix. I am trying to find beta hat, but I am confused about the response variable. 
Should the response variable be the BOLD data, or category?
@noelpimentel  @giancarloescobar  @imranyousuf @matthew-brett @rossbar

**Comment by imranyousuf** [comment]
I am not sure. Can we tag ross or Matthew to it ?

**Comment by changzheng1993** [comment]
By the way, do you know how to use ipython notebook?
@imranyousuf

**Comment by imranyousuf** [comment]
yes, I have a brief idea

**Comment by matthew-brett** [comment]
The response variable is the BOLD data.  I write the response data as `y` in the class notes or `Y` when I mean a (time by voxel) matrix.  The design matrix is always `X` in my notes.

**Comment by changzheng1993** [comment]
Thank you very much!
@matthew-brett
