### ISSUE TITLE
Meeting tomorrow @10:30 am

### ISSUE THREAD

**Issue by gcescobar13** [berkeley-stat159/project-kappa#90]
Hi @matthew-brett I was wondering if we can meet with you a little earlier tomorrow so we can have a chance to ask you plenty of questions as we reach the end of our analysis. Thank you in advance.

**Comment by matthew-brett** [comment]
Sure.  How about 11 tomorrow?

**Comment by gcescobar13** [comment]
Yes, that's perfect! We'll see you tomorrow at 11.
