### ISSUE TITLE
t-map(house-face)

### ISSUE THREAD

**Issue by changzheng1993** [berkeley-stat159/project-kappa#96]
@matthew-brett 
We got a t-map for beta_house - beta_face for each run, and  I attached the plot and code.
could you please let me know if it is correct?

Code:
hf1 = np.loadtxt('house_betas_task001_run001.txt') - np.loadtxt('face_betas_task001_run001.txt')
hf2 = np.loadtxt('house_betas_task001_run002.txt') - np.loadtxt('face_betas_task001_run002.txt')
hf3 = np.loadtxt('house_betas_task001_run003.txt') - np.loadtxt('face_betas_task001_run003.txt')
hf4 = np.loadtxt('house_betas_task001_run004.txt') - np.loadtxt('face_betas_task001_run004.txt')
hf5 = np.loadtxt('house_betas_task001_run005.txt') - np.loadtxt('face_betas_task001_run005.txt')
hf6 = np.loadtxt('house_betas_task001_run006.txt') - np.loadtxt('face_betas_task001_run006.txt')
hf7 = np.loadtxt('house_betas_task001_run007.txt') - np.loadtxt('face_betas_task001_run007.txt')
hf8 = np.loadtxt('house_betas_task001_run008.txt') - np.loadtxt('face_betas_task001_run008.txt')
hf9 = np.loadtxt('house_betas_task001_run009.txt') - np.loadtxt('face_betas_task001_run009.txt')
hf10 = np.loadtxt('house_betas_task001_run010.txt') - np.loadtxt('face_betas_task001_run010.txt')
hf11 = np.loadtxt('house_betas_task001_run011.txt') - np.loadtxt('face_betas_task001_run011.txt')
hf12 = np.loadtxt('house_betas_task001_run012.txt') - np.loadtxt('face_betas_task001_run012.txt')
matrix =np.vstack((hf1, hf2, hf3, hf4, hf5, hf6, hf7, hf8, hf9, hf10, hf11, hf12))
t_hf = t_test(matrix)
t_hf_3d = np.reshape(t_hf, (91,109,91))
plt.imshow(t_hf_3d[:,:,45])
plot:
<img width="567" alt="screen shot 2015-12-11 at 7 43 50 pm" src="https://cloud.githubusercontent.com/assets/13594791/11760045/9dd61bae-a03f-11e5-8d26-aa0400c92900.png">

**Comment by matthew-brett** [comment]
I can't say whether the code is correct - but the resulting map does look like it should, yes.

It would be good if you were able to avoid most of those very similar statements to make the 12 maps, maybe with a loop.

**Comment by gcescobar13** [comment]
@matthew-brett I am still confused what the image is telling us. What is t-map telling us?

**Comment by matthew-brett** [comment]
Those two red dots are areas where the signal (amount of the hemodyamic regressor shape in the BOLD signal) is high relative to the variance across runs.

In fact, you've just found the Parahippocampal Place area.  Have a look at the rather similar (but thresholded, displayed on anatomy) images in http://www.sciencedirect.com/science/article/pii/S0896627300807588

**Comment by gcescobar13** [comment]
Thank you for the link. Will read tonight
